"""Add note column to Withdrawal

Revision ID: 6630b47d3544
Revises: 6508542f8a65
Create Date: 2026-04-14 23:56:37.489203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6630b47d3544'
down_revision = '6508542f8a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verified')

    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.drop_column('note')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
