"""Add referral system

Revision ID: 94544b22aab5
Revises: d6cea723a96a
Create Date: 2026-04-11 17:09:31.245360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94544b22aab5'
down_revision = 'd6cea723a96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    def upgrade():
        with op.batch_alter_table('user', schema=None) as batch_op:
           batch_op.add_column(sa.Column('referral_code', sa.String(length=20), nullable=True))
           batch_op.add_column(sa.Column('referred_by', sa.Integer(), nullable=True))
           batch_op.create_unique_constraint('uq_user_referral_code', ['referral_code'])
           batch_op.create_foreign_key('fk_user_referred_by', 'user', ['referred_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_referred_by', type_='foreignkey')
        batch_op.drop_constraint('uq_user_referral_code', type_='unique')
        batch_op.drop_column('referred_by')
        batch_op.drop_column('referral_code')


    # ### end Alembic commands ###
