"""Add tutorial_seen field to User

Revision ID: f7b504703d43
Revises: cfc3f728b946
Create Date: 2026-04-15 23:41:56.782027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b504703d43'
down_revision = 'cfc3f728b946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tutorial_seen', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tutorial_seen')

    # ### end Alembic commands ###
